### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Dustin-Davis** [Dustin-Davis/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] make a index.html
- [x] make a styles.css
- [x] make a main.js
- [x] set the background color 
- [x] put a top-down image of a car on the page
